theme: jekyll-theme-minimal
show_downloads: true
github:
  zip_url: https://github.com/tbitai/elte-phil-logic-personal-website/archive/v0.1.0.zip
  tar_url: https://github.com/tbitai/elte-phil-logic-personal-website/archive/v0.1.0.tar.gz
