theme: jekyll-theme-minimal
title: ELTE Phil Logic personal website
owner_full_name: Tamás Bitai
show_downloads: true
zip_url: https://github.com/tbitai/elte-phil-logic-personal-website/archive/v0.1.0.zip
tar_url: https://github.com/tbitai/elte-phil-logic-personal-website/archive/v0.1.0.tar.gz
